project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  title: "DTRL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: "Projects"
      - href: people.qmd
        text: "People"
      - href: lab-protocol.qmd
        text: "Lab Protocol"
      - join-us.qmd

format:
  html:
    theme: styles.scss
    mainfont: M PLUS Rounded 1c
    fontcolor: "#333333"
    linkcolor: "#D5008F"
    backgroundcolor: "#f2f2f1"
    #toc: true
    page-layout: full
    sidebar: false
    css: styles.css

editor: source