---
layout: grid
---


::: {style="text-align: center;"}

# Current Research Projects {style="text-align: center;"}

***

::: grid
::: g-col-4
# {{< fa laptop-code size=lg >}} {.icon}

#### Equitable Pair Programming

::: small
We are studying how instructors can create pair programming environments that
support *every* student. 
:::
:::

::: g-col-4

# {{< fa pen-to-square size=lg >}} {.icon}

#### Groupworthy Data Science Activities

::: small
We are creating a set of data science activities that are cognitively engaging
and require multiple, diverse perspectives to complete. These activities can be
integrated alongside pair programming! 
:::
:::

::: g-col-4
# {{< fa clipboard-list size=lg >}} {.icon}

#### Increasing Cognitive Engagement in Surveys

::: small
This project is led by Otis Hunt, who is interested in exploring what survey
options / structure is associated with students engaging more in the surveys
their instructors provide. Otis was awarded the [2025 Frost Research Scholarship](https://cosam.calpoly.edu/prospective-students/frost-fund/frost-scholarship)
to continue this research. 
:::
:::
:::

<!-- <i class="fa-solid fa-"></i> -->

::: grid

::: g-col-4
# {{< fa brands r-project size=lg >}} {.icon}

#### Introduction to R

::: small
We are developing a "baby R" curriculum which introduces students to R during 
their first quarter at Cal Poly. The course has no computing pre-requisite. 
:::
:::

::: g-col-4
# {{< fa road size=lg >}} {.icon}

#### Data science trajectory

::: small
We are interested in the pathways students take when learning data science 
concepts and skills---how do concepts build on each other? What are the
key stumbling blocks?
:::
:::

::: g-col-4
# {{< fa camera-rotate size=lg >}} {.icon}

#### Students' Self Perceptions

::: small
This project was led by Jett Palmer, who was interested in exploring how an 
instructor's pedagogical methods were associated with aspects of students’
social identities (e.g., disciplinary identity). Jett presented on this 
research during the [2023 eCOTS Poster Presentations](Student Collaborative Experiences & Self-Perceptsions -- A Comparison Study of Complex Instruction).
:::
:::
:::
:::
